<?php

use Illuminate\Database\Seeder;

class BalaiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `balai` (`id`, `nmbalai`, `wilayah_id`) VALUES
        (1, 'BALAI WILAYAH SUNGAI SUMATERA I', 1),
        (2, 'BALAI WILAYAH SUNGAI SUMATERA II', 1),
        (3, 'BALAI WILAYAH SUNGAI SUMATERA III', 1),
        (4, 'BALAI WILAYAH SUNGAI SUMATERA IV', 1),
        (5, 'BALAI WILAYAH SUNGAI SUMATERA V', 1),
        (6, 'BALAI WILAYAH SUNGAI SUMATERA VI', 1),
        (7, 'BALAI WILAYAH SUNGAI SUMATERA VII', 1),
        (8, 'BALAI BESAR WILAYAH SUNGAI  SUMATERA VIII', 1),
        (9, 'BALAI BESAR WILAYAH SUNGAI MESUJI SEKAMPUNG', 1),
        (10, 'BALAI BESAR WILAYAH SUNGAI CIDANAU CIUJUNG CIDURIA', 2),
        (11, 'BALAI BESAR WILAYAH SUNGAI CILIWUNG CISADANE', 2),
        (12, 'BALAI BESAR WILAYAH SUNGAI CITARUM', 2),
        (13, 'BALAI BESAR WILAYAH SUNGAI CIMANUK CISANGGARUNG', 2),
        (14, 'BALAI BESAR WILAYAH SUNGAI CITANDUY', 2),
        (15, 'BALAI BESAR WILAYAH SUNGAI PEMALI JUANA', 2),
        (16, 'BALAI BESAR WILAYAH SUNGAI SERAYU OPAK', 2),
        (17, 'BALAI BESAR WILAYAH SUNGAI BENGAWAN SOLO', 2),
        (18, 'BALAI BESAR WILAYAH SUNGAI BRANTAS', 2),
        (19, 'BALAI WILAYAH SUNGAI BALI-PENIDA', 2),
        (20, 'BALAI WILAYAH SUNGAI NUSA TENGGARA I', 2),
        (21, 'BALAI WILAYAH SUNGAI NUSA TENGGARA II', 2),
        (22, 'BALAI WILAYAH SUNGAI KALIMANTAN I', 1),
        (23, 'BALAI WILAYAH SUNGAI KALIMANTAN II', 1),
        (24, 'BALAI WILAYAH SUNGAI KALIMANTAN III', 1),
        (25, 'BALAI WILAYAH SUNGAI SULAWESI I', 3),
        (26, 'BALAI WILAYAH SUNGAI SULAWESI II', 3),
        (27, 'BALAI WILAYAH SUNGAI SULAWESI III', 3),
        (28, 'BALAI WILAYAH SUNGAI SULAWESI IV', 3),
        (29, 'BALAI BESAR WILAYAH SUNGAI POMPENGAN JENEBERANG', 3),
        (30, 'BALAI WILAYAH SUNGAI MALUKU', 3),
        (31, 'BALAI WILAYAH SUNGAI MALUKU UTARA', 3),
        (32, 'BALAI WILAYAH SUNGAI  PAPUA', 3),
        (33, 'BALAI WILAYAH SUNGAI  PAPUA MERAUKE', 3),
        (34, 'BALAI WILAYAH SUNGAI  PAPUA BARAT', 3);");
    }
}
